### ISSUE TITLE
Payout error on v1.3.4

### ISSUE THREAD

**Issue by ilhanu** [canontech/staking-payouts#76]
Getting the following on Kusama and Polkadot. 
```
2021-09-30 07:10:14 [payouts] info: Total of 4 unclaimed payouts.
2021-09-30 07:10:14 [payouts] info: Transactions are being created. This may take some time if there are many unclaimed eras.
index.js collect

TypeError: api.consts.system.blockWeights.perClass.normal.maxExtrinsic.unwrap is not a function
    at signAndSendTxs (/home/ubuntu/git/staking-payouts/build/services.js:130:86)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.collectPayouts (/home/ubuntu/git/staking-payouts/build/services.js:37:5)
    at async Object.collect [as handler] (/home/ubuntu/git/staking-payouts/build/handlers.js:38:5)

```
Reverted back to v1.3.3 and the payouts work as intended. But then when the new runtime for Kusama enacts in and v1.3.4 works on the kusama runtime it would not be compatible with Polkadot.

**Comment by emostov** [comment]
Thank you for reporting the issue. Release v1.3.6 should fix this.
