### ISSUE TITLE
1.4.0 / 1.4.1 seems to be broken with node 18.X

### ISSUE THREAD

**Issue by Stakecraft** [canontech/staking-payouts#84]
```
node -v
v18.2.0

npm -v
8.9.0

payouts --version
1.4.1
```

PAYOUTS_DEBUG=1 payouts -w wss://kusama.api.onfinality.io/public --stashesFile kusama_validator.json -u kusama-payout.key -e 4

```
2022-05-24 16:26:43 [payouts] debug: suriFile: kusama-payout.key
2022-05-24 16:26:43 [payouts] debug: Parsed stash address: MY-ADDRESS
2022-05-24 16:26:45        API/INIT: RPC methods not decorated: beefy_getFinalizedHead, mmr_generateBatchProof, state_trieMigrationStatus
2022-05-24 16:26:45        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageEntryTypeLatest):: Invalid character
    at EventEmitter.value (/usr/lib/node_modules/@zekemostov/staking-payouts/node_modules/@polkadot/api/base/Init.cjs:86:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-05-24 16:27:45          API-WS: disconnected from wss://kusama.api.onfinality.io/public: 1006:: Connection dropped by remote peer.
2022-05-24 16:27:49        API/INIT: RPC methods not decorated: beefy_getFinalizedHead, mmr_generateBatchProof, state_trieMigrationStatus
2022-05-24 16:27:49        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageEntryTypeLatest):: Invalid character
    at EventEmitter.value (/usr/lib/node_modules/@zekemostov/staking-payouts/node_modules/@polkadot/api/base/Init.cjs:86:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-05-24 16:28:48          API-WS: disconnected from wss://kusama.api.onfinality.io/public: 1006:: Connection dropped by remote peer.
2022-05-24 16:28:52        API/INIT: RPC methods not decorated: beefy_getFinalizedHead, mmr_generateBatchProof, state_trieMigrationStatus
2022-05-24 16:28:52        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageEntryTypeLatest):: Invalid character
    at EventEmitter.value (/usr/lib/node_modules/@zekemostov/staking-payouts/node_modules/@polkadot/api/base/Init.cjs:86:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
```

any advices to fix this bug?

**Comment by emostov** [comment]
I won't have a chance to look into this closely for a little while - but can you just use node v16 in your environment?

**Comment by Stakecraft** [comment]
sure, I can try.

**Comment by Stakecraft** [comment]
unfortunately it doesn't work

**Comment by Stakecraft** [comment]
hi @emostov any chance to look into issue in the following month?

**Comment by emostov** [comment]
I can't reproduce your issue with node v16, but I put out a new release with updated deps and it works for me locally with node v18 and v16.

**Comment by minzak** [comment]
Some warnings are still the same  "API/INIT: RPC methods not decorated"
https://github.com/canontech/staking-payouts/issues/94
