### ISSUE TITLE
Payout error on v1.4.4

### ISSUE THREAD

**Issue by Serg-everstake** [canontech/staking-payouts#90]
Getting the following on Kusama and Westend. Until October 27, everything worked perfectly. 

```
2022-10-28 12:22:05 [payouts] info: Total of 2 unclaimed payouts.
2022-10-28 12:22:05 [payouts] info: Transactions are being created. This may take some time if there are many unclaimed eras.
index.js collect

Collect pending payouts

Options:
      --help         Show help                                         [boolean]
      --version      Show version number                               [boolean]
  -w, --ws           The API endpoint to connect to, e.g.
                     wss://kusama-rpc.polkadot.io            [string] [required]
  -S, --stashesFile  Path to .json file containing an array of the stash
                     addresses to call payouts for.                     [string]
  -s, --stashes      Array of stash addresses to call payouts for. Required if
                     not using stashesFile.                              [array]
  -e, --eraDepth     How many eras prior to the last collected era to check for
                     uncollected payouts.                  [number] [default: 0]
  -u, --suriFile     Path to .txt file containing private key seed.
                                                             [string] [required]

TypeError: maxExtrinsicMaybeOpt.unwrap(...).toBn is not a function
    at signAndSendTxs (/home/ubuntu/git/staking-payouts/build/services.js:282:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async collectPayouts (/home/ubuntu/git/staking-payouts/build/services.js:41:5)
    at async Object.collect [as handler] (/home/ubuntu/git/staking-payouts/build/handlers.js:38:5)
```

**Comment by emostov** [comment]
Thanks for reporting. Confirming this is an issue. Will fix soon

**Comment by hitchhooker** [comment]
what is the deal with these runtime upgrades breaking payouts? what changes it requires for the code? more than new metadata? gets always a bit stressful to do these manually so would be keen to contribute if knew better.
