### ISSUE TITLE
Error claiming payouts

### ISSUE THREAD

**Issue by sagarbutt** [canontech/staking-payouts#98]
Hi @emostov It was working very good for a long time but suddenly yesterday at 2024-04-18 11:33 CEST stopped working for Kusama, the error is `TypeError: Cannot read properties of undefined (reading 'toArray') `and the full trace:
```
2024-04-18 11:33:02        API/INIT: RPC methods not decorated: chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties
2024-04-18 11:33:02        API/INIT: kusama/1002000: Not decorating runtime apis without matching versions: BeefyApi/3 (1/2 known), ParachainHost/10 (1/2/3/4 known)
2024-04-18 11:33:02        API/INIT: kusama/1002000: Not decorating unknown runtime apis: 0xfbc577b9d747efd6/1
index.js collect

Collect pending payouts

Commands:
  index.js collect       Collect pending payouts                       [default]
  index.js ls            List pending payouts
  index.js lsNominators  List nominators backing the given stashes
  index.js commission    List validators with commission under and above the
                         given value

Options:
      --help         Show help                                         [boolean]
      --version      Show version number                               [boolean]
  -w, --ws           The API endpoint to connect to, e.g.
                     wss://kusama-rpc.polkadot.io            [string] [required]
  -S, --stashesFile  Path to .json file containing an array of the stash
                     addresses to call payouts for.                     [string]
  -s, --stashes      Array of stash addresses to call payouts for. Required if
                     not using stashesFile.                              [array]
  -e, --eraDepth     How many eras prior to the last collected era to check for
                     uncollected payouts.                  [number] [default: 0]
  -u, --suriFile     Path to .txt file containing private key seed.
                                                             [string] [required]

TypeError: Cannot read properties of undefined (reading 'toArray')
    at listPendingPayouts (/opt/staking-payouts/build/services.js:84:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectPayouts (/opt/staking-payouts/build/services.js:31:21)
    at async Object.collect [as handler] (/opt/staking-payouts/build/handlers.js:38:5)
```
It still works in Polkadot though, the error is just in Kusama.

Thank you very much

**Comment by emostov** [comment]
Thank you for pointing out the issue! I currently am swamped with my normal work but will work on updating this when I get a free moment

**Comment by johnuopini** [comment]
@emostov thanks, made a quick fix, i am not good in TS so its probably not optimal but it works
